controller_list:
  - name: rokae_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
  - name: inspire_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - Big_Thump_Joint1
      - Big_Thump_Joint2
      - Big_Thump_Joint3
      - Big_Thump_Joint4
      - Index_Finger_Joint1
      - Index_Finger_Joint2
      - Little_Thump_Joint1
      - Little_Thump_Joint2
      - Middle_Finger_joint1
      - Middle_Finger_joint2
      - Ring_Finger_Joint1
      - Ring_Finger_Joint2